name: CD Pipeline for Recommendation system

on:
    workflow_run:
      workflows: ["CI Pipeline for Recommendation system"]
      types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull anusha562/recommendation_system-cicd-pipeline:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container anusha562/recommendation_system-cicd-pipeline:latest
