name: CD Pipeline for Recommendation system

on:
    workflow_run:
      workflows: ["CI Pipeline for Recommendation system"]
      types:
        - completed

jobs:

  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull anusha562/recommendation_system-cicd-pipeline:latest

    - name: Stop Old Docker Container
      run: sudo docker stop cicd-pipeline-container || true

    - name: Delete Old Docker Container
      run: sudo docker rm -f cicd-pipeline-container || true

    - name: Run Docker Container
      run: |
        sudo docker run -d -p 8501:8501 \
        -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        --name cicd-pipeline-container \
        anusha562/recommendation_system-cicd-pipeline:latest

    - name: Verify Application Deployment
      run: |
        sleep 10  # Wait for the app to start
        curl -f http://localhost:8501 || (echo "Application failed to start" && exit 1)
