name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up DVC
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install dvc[s3]

    - name: Configure DVC with S3 bucket
      run: |
        dvc remote add -d myremote s3://dvc-recommendation-files 
        dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Pull data from DVC (S3)
      run: dvc pull --remote myremote

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build -t anusha562/recommendation_system-cicd-pipeline:latest .
      
    - name: Push to Dockerhub
      run: docker push anusha562/recommendation_system-cicd-pipeline:latest
